### ISSUE TITLE
No matching version found for serial-io@^2.0.0

### ISSUE THREAD

**Issue by drpodmeer** [anoff/serial-io#53]
Hi there, 

thanks for your wonderful plug-in homebridge-benq-projector, it worked always really well. but now, if i want to update to the latest update i get following error. 

thanks in advanced. 

Cheers! 

------------------------------------------

USER: homebridge
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-benq-projector@latest

npm ERR! code ETARGET
npm ERR! notarget No matching version found for serial-io@^2.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-11-17T18_46_40_184Z-debug.log

Command failed. Please review log for details.

**Comment by anoff** [comment]
Hey @drpodmeer I think you have opened this issue in the wrong repo :)
Actually it is the `homebridge-benq-projector` repo that is trying to access an unreleased version of *this* repo (serial-io).

see related issue: https://github.com/solowalker27/homebridge-benq-projector/issues/9
